Replace '<xsl:value-of/>' with '<value-of/>' to fix diagnostics
elifesciences/reference-schematron pull request #9
Opened 2018-06-19 13:08 UTC by garyttierney

Uses the un-namespaced version of '<value-of/>' to avoid situations where the
<value-of> tag is stripped out before the validation stage.  This occurs in
http://phax.github.io/ph-schematron/ where the SCH file is passed through
several preparation stages and the <xsl:value-of> is wrongly evaluated and
stripped out during the 3rd.

cc @nlisgo @JGilbert-eLife -- this will fix the diagnostic messages, however, makes it hard to write a test that `<xsl:value-of/>` won't be used it on.  I have a WIP change in `schematron-validator` that'll try to convert any input SCH files using the namespaced version to the freestanding version.

2018-06-20 11:16 UTC, nlisgo commented
I will have to speak with @JGilbert-eLife to see if this change is welcomed. Essentially, does it still work when used in OxygenXML and any other standard methods of running the schematron.

2018-06-20 12:33 UTC, garyttierney commented
@nlisgo yep, it will still run correctly (tested via CLI).  `value-of` is [defined](http://www.datypic.com/sc/schematron/e-sch_value-of.html) in the schematron XSD, so it'll simply resolve to `sch:value-of` instead.  There should be no change for any software that simply transforms the SCH to XSLT (the difference in `schematron-validator` is that it transforms the SCH -> XSLT and then tries to parse semantic information from it).

2018-06-27 11:24 UTC, nlisgo requested changes
Apologies for the delay in review. We want to recommend that this is implemented.

If we are no longer using the `xsl` namespace then we could remove it's declaration.

```
<pattern
   id="element-citation-book-pre-edit-tests"
   xmlns="http://purl.oclc.org/dsdl/schematron"
   xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
```

would become: 

```
<pattern
   id="element-citation-book-pre-edit-tests"
   xmlns="http://purl.oclc.org/dsdl/schematron">
```

2018-06-28 14:17 UTC, JGilbert-eLife reviewed
This is just to confirm that I've found no detrimental effects of removing the xsl: namespace when running the schematron files in Oxygen. We'll be talking to someone more knowledgeable about schematron this time next week to see if they can advise on when it would be preferable to use xsl:value-of over sch:value-of.

2018-07-13 10:00 UTC, JGilbert-eLife commented
I can confirm having consulted the more knowledgeable person I mentioned that there should be no problem stripping out the XSL namespace.

2018-07-13 10:01 UTC, garyttierney commented
Ah, didn't realise that the XSL namespace was only used for that single element.  I'll remove that and we can get it merged.  Cheers!

2018-07-16 13:11 UTC, garyttierney commented
cc @nlisgo should be ok to merge now per @JGilbert-eLife's feedback above, and I've removed the unused XMLNS.

2018-07-17 09:29 UTC, nlisgo approved these changes

2018-07-18 15:08 UTC, merged